project_id = "oqvvffeaffyoapdtpmjr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.process-document]
verify_jwt = false

[functions.public-chat]
verify_jwt = false

[functions.api-spaces]
verify_jwt = false

[functions.api-links]
verify_jwt = false

[functions.api-documents]
verify_jwt = false

[functions.api-analytics]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.api-admin]
verify_jwt = false

[functions.scrape-url]
verify_jwt = false

[functions.app-assistant]
verify_jwt = false